services:
  # Our Backend Box
  backend:
    build:
      context: ./backend # Tells Docker where to find the backend Dockerfile
    ports:
      - "8080:8080" # Opens a door so your computer can reach the backend ( the https port from the backend launchSettings.json )
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=true  
      
  # Our Frontend Box
  frontend:
    build:
      context: ./frontend # Tells Docker where to find the frontend Dockerfile
    ports:
      - "5173:5173" # Maps the frontend's window to port 5173 on your computer
    volumes:
      - ./frontend:/app
      - /app/node_modules # This keeps the heavy Node tools safely inside the box so they don't clutter your computer.
    depends_on:
      - backend # Tells the frontend to wait nicely for the backend to wake up first