networks:
  web_network:
    external: false

volumes:
  jenkins_data: # Define the volume for persistent data

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    restart: always
    privileged: true
    user: root
    # Nginx will communicate via the internal docker network.
    ports:
      - "50000:50000"  #for Jenkins agents
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins:ro
    networks:
      - web_network # Linked to the same network as Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./certbot-etc:/etc/letsencrypt:ro        # Where Nginx reads the production certificates
      - ./certbot-var:/var/www/certbot:ro        # Where Nginx serves the ACME verification files
    networks:
      - web_network
  # Our Backend Box
  backend:
    build:
      context: ./backend # Tells Docker where to find the backend Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=true  
    networks:
      web_network:
        aliases:
          - backend
      
  # Our Frontend Box
  frontend:
    build:
      context: ./frontend # Tells Docker where to find the frontend Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # This keeps the heavy Node tools safely inside the box so they don't clutter your computer.
    depends_on:
      - backend # Tells the frontend to wait nicely for the backend to wake up first
    networks:
      web_network:
        aliases:
          - frontend